import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:3187';
const credentials={username:'community-admin',password:'Testpasswort-Community-123!'};
test('Fresh installation, private data, persisted edits and member permissions',async({page,request,browser})=>{
 await page.goto('/setup');
 await expect(page.getByRole('heading',{name:'Dein Administratorkonto'})).toBeVisible();
 for(const path of ['/api/vault','/api/settings','/api/users','/api/images/11111111-1111-4111-8111-111111111111.jpg'])expect((await request.get(path)).status()).toBe(401);
 for(const path of ['/api/analysis','/api/capture','/api/motion','/api/upload'])expect((await request.post(path,{headers:{origin},data:{}})).status()).toBe(401);
 const wrong=await request.post('/api/setup',{headers:{origin},data:{token:'wrong',name:'Test',...credentials}});expect(wrong.status()).toBe(403);
 await page.getByLabel('Einrichtungsschlüssel').fill('test-only-setup-token-never-for-production');
 await page.getByLabel('Dein Name').fill('Community Test');
 await page.getByLabel('Benutzername',{exact:true}).fill(credentials.username);
 await page.getByLabel('Passwort',{exact:true}).fill(credentials.password);
 await page.getByRole('button',{name:'Library einrichten',exact:true}).click();
 await expect(page).toHaveURL(/\/settings$/);
 await expect(page.getByRole('heading',{name:'KI & Website-Aufnahmen'})).toBeVisible();
 const api=page.context().request;
 const again=await api.post('/api/setup',{headers:{origin},data:{token:'test-only-setup-token-never-for-production',name:'Attacker',username:'another-admin',password:credentials.password}});expect(again.status()).toBe(409);
 const vault=await (await api.get('/api/vault')).json();expect(vault.entries).toHaveLength(34);expect(vault.collections).toHaveLength(10);expect(vault.entries.some((e:{title:string})=>e.title==='Linear')).toBeTruthy();
 await page.goto('/');await expect(page.getByRole('heading',{name:'Alle Referenzen 34',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Referenz hinzufügen',exact:true})).toBeEnabled();
 await expect(page.getByRole('button',{name:'Linear ansehen',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Linear ansehen',exact:true}).click();
 await expect(page.getByText('Designprofil bearbeiten',{exact:true})).toBeVisible();
 await page.getByText('Designprofil bearbeiten',{exact:true}).click();
 await page.getByLabel('Titel',{exact:true}).fill('Linear · eigener Entwurf');
 await page.getByRole('button',{name:'Designprofil speichern',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Linear · eigener Entwurf',exact:true}).first()).toBeVisible();
 await page.reload();
 await expect(page.getByRole('button',{name:'Linear · eigener Entwurf ansehen',exact:true})).toBeVisible();
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/library-desktop.png',fullPage:false});
 const prefs={includeDna:true,constants:'Eigene dauerhafte Vorliebe',never:'Unlesbare Texte',overrides:'Testprojekt'};
 expect((await api.put('/api/preferences',{headers:{origin},data:prefs})).ok()).toBeTruthy();
 const member=await (await api.post('/api/users',{headers:{origin},data:{name:'Team Test',username:'team-test',role:'member'}})).json();expect(member.temporaryPassword).toBeTruthy();
 const context=await browser.newContext();const memberApi=context.request;
 expect((await memberApi.post(origin+'/api/auth/login',{headers:{origin},data:{username:'team-test',password:member.temporaryPassword}})).ok()).toBeTruthy();
 expect((await memberApi.get(origin+'/api/settings')).status()).toBe(403);
 expect((await memberApi.put(origin+'/api/account',{headers:{origin},data:{name:'Team Test',currentPassword:member.temporaryPassword,password:'Changed-Member-Password-123!'}})).ok()).toBeTruthy();
 expect((await memberApi.get(origin+'/api/vault')).ok()).toBeTruthy();
 expect((await memberApi.delete(origin+'/api/references',{headers:{origin},data:{id:'community-01'}})).status()).toBe(403);
 const settings=await (await api.get('/api/settings')).json();expect(settings.provider).toBe('openai');expect(settings.configured).toBe(false);
 expect((await api.put('/api/settings',{headers:{origin},data:{...settings,provider:'anthropic',model:'claude-sonnet-4-20250514',enabled:false,browserKey:'test-browserless-key-never-valid'}})).ok()).toBeTruthy();
 const stored=await (await api.get('/api/settings')).json();expect(stored.browserConfigured).toBe(true);expect(JSON.stringify(stored)).not.toContain('test-browserless-key');
 const csrf=await api.put('/api/preferences',{headers:{origin:'https://untrusted.example'},data:prefs});expect(csrf.status()).toBe(403);
 expect((await api.delete('/api/references',{headers:{origin},data:{id:'community-01'}})).ok()).toBeTruthy();
 expect((await (await api.get('/api/vault')).json()).entries).toHaveLength(33);
 await api.post('/api/auth/logout',{headers:{origin}});
 expect((await api.get('/api/vault')).status()).toBe(401);
 expect((await api.post('/api/auth/login',{headers:{origin},data:credentials})).ok()).toBeTruthy();
 const restored=await (await api.get('/api/vault')).json();expect(restored.entries).toHaveLength(33);expect(restored.preferences.constants).toBe(prefs.constants);expect(restored.entries.find((e:{title:string})=>e.title==='Linear · eigener Entwurf')).toBeTruthy();
 await context.close();
 await page.goto('/');await expect(page.getByRole('button',{name:'Referenz hinzufügen',exact:true})).toBeEnabled();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/library-mobile.png'});
});
