import type {Provider} from './analysis-server';
type Config={apiKey?:string;model:string;provider:Provider};
export async function analyzeJson(config:Config,instruction:string,images:string[],schema:Record<string,unknown>,name:string){
 if(!config.apiKey)throw Error('Bitte zuerst einen API-Schlüssel speichern.');
 const anthropic=config.provider==='anthropic';
 const response=await fetch(anthropic?'https://api.anthropic.com/v1/messages':'https://api.openai.com/v1/responses',{
 method:'POST',headers:anthropic?{'x-api-key':config.apiKey,'anthropic-version':'2023-06-01','Content-Type':'application/json'}:{Authorization:'Bearer '+config.apiKey,'Content-Type':'application/json'},signal:AbortSignal.timeout(120000),cache:'no-store',
 body:JSON.stringify(anthropic?{model:config.model,max_tokens:8000,system:instruction,tools:[{name,description:'Gib die vollständige strukturierte Designanalyse aus.',input_schema:schema}],tool_choice:{type:'tool',name},messages:[{role:'user',content:[{type:'text',text:'Analysiere diese Referenzbilder.'},...images.map(s=>({type:'image',source:{type:'base64',media_type:'image/jpeg',data:s.split(',')[1]}}))]}]}:{model:config.model,store:false,max_output_tokens:8000,instructions:instruction,input:[{role:'user',content:[{type:'input_text',text:'Analysiere diese Referenzbilder.'},...images.map(image_url=>({type:'input_image',image_url,detail:'high'}))]}],text:{format:{type:'json_schema',name,strict:true,schema}}})});
 if(!response.ok)throw Error(response.status===401||response.status===403?'API-Schlüssel oder Berechtigungen sind ungültig. Bitte Einstellungen prüfen.':response.status===429?'Das API-Nutzungs- oder Guthabenlimit ist erreicht.':response.status===404?'Dieses Modell ist für dein API-Konto nicht verfügbar.':'Der KI-Anbieter konnte die Analyse nicht abschließen. Prüfe, ob dein Modell Bilder und strukturierte Antworten unterstützt.');
 const body=await response.json();
 if(anthropic){if(body.stop_reason!=='tool_use')throw Error('Unvollständige KI-Antwort.');const block=body.content?.find((c:{type:string;name:string})=>c.type==='tool_use'&&c.name===name);if(!block)throw Error('Keine strukturierte Analyse erhalten.');return block.input;}
 if(body.status!=='completed')throw Error('Unvollständige KI-Antwort.');return JSON.parse((body.output||[]).flatMap((o:{content?:{type:string;text?:string}[]})=>o.content||[]).filter((c:{type:string})=>c.type==='output_text').map((c:{text:string})=>c.text).join(''));
}
export async function providerModels(provider:Provider,key:string){const r=await fetch(provider==='anthropic'?'https://api.anthropic.com/v1/models?limit=100':'https://api.openai.com/v1/models',{headers:provider==='anthropic'?{'x-api-key':key,'anthropic-version':'2023-06-01'}:{Authorization:'Bearer '+key},signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error('Schlüssel oder Modellzugriff konnten nicht geprüft werden.');const d=await r.json();return (d.data||[]).map((m:{id:string;display_name?:string})=>({id:m.id,name:m.display_name||m.id})).sort((a:{id:string},b:{id:string})=>a.id.localeCompare(b.id));}
