import {motionBrief,type Motion,type MotionCapture} from './motion';
import seed from '@/data/gallery.json';
export type Collection=typeof seed.collections[number];
export type Entry=Omit<typeof seed.entries[number],"motion"|"screenshotKind"|"sourceUrl"|"captureNote">&{uploaded?:boolean;sourceUrl?:string;screenshotKind?:"section"|"full-page";captureNote?:string;motion?:Motion;motionCapture?:MotionCapture;fullPageFile?:string};
export type Preferences={includeDna:boolean;overrides:string;constants:string;never:string};
export const defaults:Preferences={includeDna:false,overrides:'',constants:seed.dna.constants.join('\n'),never:seed.dna.never.join('\n')};
export const imagePath=(e:Entry)=>e.uploaded?'/api/images/'+e.file:'/images/'+e.file;
export const referencePath=(e:Entry)=>typeof window==='undefined'?imagePath(e):window.location.origin+imagePath(e);
export function preferenceBrief(p:Preferences){return [p.includeDna?`Allgemeine Vorlieben (Ausgangspunkt, keine starren Regeln):\n${p.constants}\nÜblicherweise vermeiden:\n${p.never}`:'',p.overrides.trim()?`Projektspezifische Vorgaben (haben Vorrang):\n${p.overrides}`:'','Folge den ausgewählten Referenzen und ausdrücklichen Projektvorgaben, wenn sie von den allgemeinen Vorlieben abweichen.'].filter(Boolean).join('\n\n');}
export function buildBrief(entries:Entry[],p:Preferences){return `Erstelle [Website oder Produkt beschreiben] für [Zielgruppe].\nWichtigste Handlung: [Was die Besucher tun sollen].\nBenötigte Inhalte: [Abschnitte und Texte].\n\n${entries.map(e=>`Referenz: ${e.title}\nBildschirmaufnahme: ${referencePath(e)}\nOriginalwebsite: ${e.sourceUrl||'Nicht hinterlegt'}\nUmfang: ${e.screenshotKind==='full-page'?'Komplette Seite':'Seitenausschnitt'}${e.fullPageFile?'\nKompletter Screenshot: '+(typeof window!=='undefined'?window.location.origin:'')+'/api/images/'+e.fullPageFile:''}\nÄsthetik: ${e.family}\nDesignvokabular: ${e.vocabulary.join(', ')}\nZu übernehmende Idee: ${e.note}\nKomposition: ${e.heroUsage}\nBildrezept: ${e.imageRecipe}\n\n${motionBrief(e.motion)}${e.motionCapture?"\nBewegungsaufnahme (privat): "+(typeof window!=="undefined"?window.location.origin:"")+"/api/images/"+e.motionCapture.videoFile:""}`).join('\n\n---\n\n')}\n\n${entries.length>1?'Verwende diese Bilder als Referenzgruppe. Wenn sie unterschiedliche Ästhetiken zeigen, entwickle zuerst eine Gestaltungsrichtung je Referenz und wähle anschließend eine aus. Vermische die Stile nicht automatisch.\n\n':''}${preferenceBrief(p)}\n\nBetrachte die Referenzbilder vor dem Entwerfen. Die Bildschirmaufnahmen liegen in einer privaten Bibliothek. Falls dein Werkzeug eine Adresse nicht öffnen kann, bitte mich, das Bild als Anhang bereitzustellen. Übernimm die visuelle Behandlung und Hierarchie, schreibe aber für unser Produkt und verwende unsere Inhalte. Übernimm keine beispielhaften Werbeaussagen oder Kundenempfehlungen. Erstelle bei Bedarf eigene Bildmotive. Setze echte responsive HTML-Texte, Bedienelemente und Komponenten um. Prüfe das Ergebnis auf Desktop- und Mobilgeräten.`;}
