'use client';
import {useState} from 'react';
import type {Entry} from '@/lib/briefs';
import {motionBrief,triggers,confidenceLabels,type Motion} from '@/lib/motion';
export const emptyMotion:Motion={summary:'',limitations:'',method:'manual',effects:[]};
export function MotionFields({value,onChange}:{value:Motion;onChange:(v:Motion)=>void}){return <div className="motion-fields"><h3>Bewegung & Interaktion</h3><label>Zusammenfassung<textarea maxLength={3000} value={value.summary} onChange={e=>onChange({...value,summary:e.target.value})}/></label>{value.effects.map((effect,i)=><fieldset key={i} className="motion-effect"><legend>Effekt {i+1}</legend>{(['name','location','description','recipe'] as const).map(key=><label key={key}>{{name:'Name',location:'Bereich / Abschnitt',description:'Beobachteter Ablauf',recipe:'Umsetzungsidee / Prompt'}[key]}<textarea required={key==='name'} maxLength={{name:120,location:300,description:2000,recipe:2500}[key]} value={effect[key]} onChange={e=>onChange({...value,effects:value.effects.map((v,n)=>n===i?{...v,[key]:e.target.value}:v)})}/></label>)}<label>Auslöser<select value={effect.trigger} onChange={e=>onChange({...value,effects:value.effects.map((v,n)=>n===i?{...v,trigger:e.target.value as typeof effect.trigger}:v)})}>{Object.entries(triggers).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Verlässlichkeit<select value={effect.confidence} onChange={e=>onChange({...value,effects:value.effects.map((v,n)=>n===i?{...v,confidence:e.target.value as typeof effect.confidence}:v)})}>{Object.entries(confidenceLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button type="button" className="text-btn" onClick={()=>onChange({...value,effects:value.effects.filter((_,n)=>n!==i)})}>Effekt entfernen</button></fieldset>)}<button type="button" className="secondary-btn" disabled={value.effects.length>=12} onClick={()=>onChange({...value,effects:[...value.effects,{name:'Neuer Effekt',location:'',trigger:'unknown',description:'',recipe:'',confidence:'unverified'}]})}>Effekt ergänzen</button><label>Grenzen der Prüfung<textarea maxLength={3000} value={value.limitations} onChange={e=>onChange({...value,limitations:e.target.value})}/></label></div>}
export function MotionPanel({entry,onSaved,onCopy}:{entry:Entry;onSaved:(e:Entry)=>void;onCopy:(text:string)=>void}){
 const[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function capture(){setBusy(true);setMessage('');try{const r=await fetch('/api/motion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:entry.id})});const d=await r.json();if(!r.ok)throw Error(d.error);onSaved(d.entry);setMessage(d.warning||'Bewegungsaufnahme gespeichert. Vorhandene Beschreibungen bleiben erhalten.');}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const m=entry.motion,c=entry.motionCapture;
 return <section className="motion-panel"><h3>Bewegung & Interaktion</h3><p>{m?.summary||'Noch nicht untersucht. Ein Screenshot allein zeigt keine verlässlichen Bewegungsabläufe.'}</p>{m?.effects.map((e,i)=><article className="motion-effect" key={i}><div className="tags"><span>{confidenceLabels[e.confidence]}</span><span>{triggers[e.trigger]}</span></div><h4>{e.name}</h4><p className="subtle">{e.location}</p><p>{e.description}</p><details><summary>Umsetzungsidee</summary><p>{e.recipe||'Noch nicht beschrieben.'}</p></details></article>)}{m?.limitations&&<p className="subtle">Grenzen: {m.limitations}</p>}{m&&<p className="subtle">Prüfmethode: {m.method==='manual-browser'?'Interaktive Browser-Prüfung':m.method==='sequence-ai'?'KI-Auswertung einer Browser-Bildfolge':'Manuell ergänzt'}. Umsetzungsideen sind keine ausgelesenen Originalcodes.</p>}{c&&<><video className="motion-video" controls playsInline preload="none" src={'/api/images/'+c.videoFile}/><p className="subtle">Aufgenommen am {new Date(c.capturedAt).toLocaleDateString('de-DE')} · {c.viewport.width} × {c.viewport.height} · {c.coverage}</p><div className="motion-frames">{c.frames.map((f,i)=><a href={'/api/images/'+f.file} key={f.file} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/images/'+f.file} alt={`Schlüsselbild ${i+1}, native Dokumentposition ${f.position} Pixel`}/><span>{f.seconds} s</span></a>)}</div><p className="subtle">Die Zeitangaben beziehen sich auf den Clip. Bei individuell animierten Scroll-Containern kann die native Dokumentposition unverändert bleiben.</p></>}<div className="row-actions"><button className="secondary-btn" disabled={!entry.sourceUrl||busy} onClick={capture}>{busy?'Bewegung wird aufgenommen …':c?'Bewegung erneut aufnehmen':'Bewegung aufnehmen & untersuchen'}</button>{m&&<button className="secondary-btn" onClick={()=>onCopy(motionBrief(m))}>Bewegungsprompt kopieren</button>}</div><p className="subtle">Kurzer Scroll-Clip mit Schlüsselbildern. Ohne vorhandene Effektbeschreibung wird die Bildfolge bei aktivierter KI analysiert. Dauer bis zu vier Minuten. Klick- und Hover-Effekte ergänzt du unter „Designprofil bearbeiten“.</p>{message&&<p role="status">{message}</p>}</section>;
}
