'use client';
import {useState,type FormEvent} from 'react';
import {MotionFields,emptyMotion} from './motion-panel';
import {Pencil} from 'lucide-react';
import type {Entry,Collection} from '@/lib/briefs';
export function ReferenceEditor({entry,collections,onSaved}:{entry:Entry;collections:Collection[];onSaved:(entry:Entry)=>void}){
 const[draft,setDraft]=useState({...entry,vocabulary:entry.vocabulary.join(', ')}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const form=new FormData();form.set('id',entry.id);form.set('sourceUrl',entry.sourceUrl||'');form.set('metadata',JSON.stringify({...draft,sourceUrl:entry.sourceUrl||'',screenshotKind:entry.screenshotKind||'section',vocabulary:draft.vocabulary.split(',').map(s=>s.trim()).filter(Boolean)}));const r=await fetch('/api/references',{method:'PATCH',body:form});const d=await r.json();if(!r.ok)throw Error(d.error);onSaved(d.entry);setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="reference-editor"><summary><Pencil size={14}/> Designprofil bearbeiten</summary><form className="vault-form" onSubmit={submit}><label>Titel<input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Sammlung<select value={draft.collection} onChange={e=>setDraft({...draft,collection:e.target.value})}>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Stil / Einordnung<input maxLength={250} value={draft.family} onChange={e=>setDraft({...draft,family:e.target.value})}/></label><label>Die Idee dahinter<textarea rows={4} maxLength={5000} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><label>Designvokabular<input maxLength={4800} value={draft.vocabulary} onChange={e=>setDraft({...draft,vocabulary:e.target.value})}/><small>Begriffe mit Kommas trennen.</small></label><label>Komposition & Platzierung<textarea rows={4} maxLength={5000} value={draft.heroUsage} onChange={e=>setDraft({...draft,heroUsage:e.target.value})}/></label><label>Bildrezept<textarea rows={4} maxLength={5000} value={draft.imageRecipe} onChange={e=>setDraft({...draft,imageRecipe:e.target.value})}/></label><MotionFields value={draft.motion||emptyMotion} onChange={motion=>setDraft({...draft,motion:{...motion,method:'manual'}})}/>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status">Designprofil gespeichert.</p>}<button className="primary-btn" disabled={busy}>{busy?'Wird gespeichert …':'Designprofil speichern'}</button></form></details>;
}
