'use client';
import {attachImage} from '@/lib/upload-client';
import {useState,type FormEvent} from 'react';
import {ArrowUpRight} from 'lucide-react';
import type {Entry} from '@/lib/briefs';
export function ReferenceSource({entry,onSaved}:{entry:Entry;onSaved:(e:Entry)=>void}){
 const[url,setUrl]=useState(entry.sourceUrl||''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const form=new FormData();form.set('id',entry.id);form.set('sourceUrl',url);if(file)await attachImage(form,'fullPage',file);const r=await fetch('/api/references',{method:'PATCH',body:form});const d=await r.json() as {entry:Entry;error?:string};if(!r.ok)throw Error(d.error||'Speichern fehlgeschlagen.');onSaved(d.entry);setFile(null);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.');}finally{setBusy(false);}}
 async function capture(){setBusy(true);setError('');setSaved(false);try{const r=await fetch('/api/capture-reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:entry.id})});const d=await r.json();if(!r.ok)throw Error(d.error);onSaved(d.entry);setSaved(true);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="reference-source">{entry.sourceUrl&&<a className="secondary-btn" href={entry.sourceUrl} target="_blank" rel="noopener noreferrer">Originalwebsite öffnen <ArrowUpRight size={15}/></a>}{entry.sourceUrl&&<button type="button" className="secondary-btn" disabled={busy} onClick={capture}>{busy?'Website wird aufgenommen …':'Website aufnehmen'}</button>}{error&&<p className="form-error" role="alert">{error}</p>}<details><summary>{entry.sourceUrl?'Link & kompletten Screenshot bearbeiten':'Link & kompletten Screenshot ergänzen'}</summary><form onSubmit={submit} className="vault-form"><label>Originalwebsite (optional)<input type="url" maxLength={2048} placeholder="https://beispiel.de" value={url} onChange={e=>{setUrl(e.target.value);setSaved(false)}} disabled={busy}/></label><label>Kompletter Website-Screenshot<input key={entry.fullPageFile||'empty'} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setSaved(false)}}/></label><p className="subtle">PNG, JPEG oder WebP bis 50 MB. Der vorhandene Ausschnitt bleibt erhalten. Ein neuer kompletter Screenshot ersetzt die bisherige Zusatzansicht.</p>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status">Gespeichert.</p>}<button className="secondary-btn" type="submit" disabled={busy}>{busy?'Wird gespeichert …':'Ergänzungen speichern'}</button></form></details></section>;
}
